name: topsheet_view
description: flutter package for top sheet view and bottom view sheet.
#author: Sonu Kumar
homepage: https://github.com/infoskillstechnology/top_sheet_view.git
version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.infoskillstechnology.top_sheet_view.top_sheet_view
    iosBundleIdentifier: com.infoskillstechnology.topsheetview.topSheetView
